name: Controlling workflow and job execution

on: [push]

jobs:
    job1:   
        runs-on: ubuntu-latest
        steps:
            - name: step 1
              run: echo "step 1"
    jobA:
      runs-on: ubuntu-latest
      steps: 
        - name: step A
          run: echo "Step A"

        - name: step B
          id: step-b
          run: |
            echo "steps.step-b.outcome ${{ steps.step-b.outcome }}"
            test 1 -eq 2

        - name: step C
          if: failure() && steps.step-b.outcome == 'failure'
          run: echo "Step C" 
    jobB:
      needs: [jobA]
      runs-on: ubuntu-latest
      steps:
        - name: step B
          run: echo 'step B'
    jobC:
      needs: [jobB]
      runs-on: ubuntu-latest
      steps:
        - name: step C
          run: echo 'step C'
    job1D:
      needs: [jobC]
      runs-on: ubuntu-latest
      steps:
        - name: step 1D
          run: echo 'step 1D'