name: Check variables

on: [push]

env:
  DAY_OF_WEEK: Monday
  First_Name: Medul

jobs:
  Variable-Check:
    runs-on: ubuntu-latest

    env:
      Greeting: Hello
      SUPER_SECRET: ${{ secrets.SUPERSECRET }}

    steps:
      - name: "Say Hello Mona it's Monday"
        run: |
          echo "$Greeting ${{ env.First_Name }}. Today is $DAY_OF_WEEK! $GITHUB_ACTION"
          echo example-command "$SUPER_SECRET"
